### ISSUE TITLE
Error after loading FNIS list.

### ISSUE THREAD

**Issue by Kazyachka** [Monitor144hz/AnimlistTransitionTool#5]
Yes, it's me again, hi @Monitor144hz. In general, this is probably the same error as with Pandora. But only in this case there is no crash, but a red window with an error appears after loading FNIS txt. And this error occurs constantly and it has nothing to do with NET. (already checked)

https://pastebin.com/0yJij8mB

![Untitled](https://github.com/Monitor144hz/AnimlistTransitionTool/assets/150479122/0068b19b-af2e-4e25-b93d-c533d742d776)

**Comment by xygb233** [comment]
1. only ostim
2. use first person
